baseURL = 'https://garethbrooksfabrication.netlify.app/'
languageCode = 'en-us'
title = 'Gareth Brooks Fabrication'
theme = "ananke"

[params]
  background_color_class = "bg-black"
  recent_posts_number = 3
